# Generated by Django 5.0.4 on 2024-05-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listings_delete_productlisting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listings',
            options={'verbose_name_plural': 'Listings'},
        ),
    ]
