# Generated by Django 5.0.4 on 2024-05-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='main_photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='photo_1',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
