# Generated by Django 5.0.4 on 2024-05-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listings_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='user',
        ),
    ]
