# Generated by Django 5.0.4 on 2024-05-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
